version: '3'

services:
  web:
    build: .
    ports:
      - "1337:3000"
    depends_on:
      - mongodb

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

  mongodb:
    image: mongo


