version: '3'
services:
  sqltest: 
    build: .
    container_name: sqltest
    ports:
      - 1337:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sqltest
      MYSQL_USER: user
      MYSQL_PASSWORD: youtu.be/l11uaEjA-iI
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
